<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN7BGaZx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN7BGaZx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerN7BGaZx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerN7BGaZx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerN7BGaZx\App_KernelProdContainer([
    'container.build_hash' => 'N7BGaZx',
    'container.build_id' => '86fd1559',
    'container.build_time' => 1741692180,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN7BGaZx');
