<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_facture' => [[], ['_controller' => 'App\\Controller\\FactureController::index'], [], [['text', '/facture']], [], [], []],
    'app_facture_create' => [[], ['_controller' => 'App\\Controller\\FactureController::create'], [], [['text', '/facture/create']], [], [], []],
    'app_facture_update' => [['id'], ['_controller' => 'App\\Controller\\FactureController::update'], [], [['text', '/update'], ['variable', '/', '[^/]++', 'id', true], ['text', '/facture']], [], [], []],
    'app_facture_delete' => [['id'], ['_controller' => 'App\\Controller\\FactureController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/facture']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_item_index' => [['factureId'], ['_controller' => 'App\\Controller\\ItemController::index'], [], [['text', '/item/index'], ['variable', '/', '[^/]++', 'factureId', true], ['text', '/facture']], [], [], []],
    'app_item_create' => [['factureId'], ['_controller' => 'App\\Controller\\ItemController::create'], [], [['variable', '/', '[^/]++', 'factureId', true], ['text', '/item/create']], [], [], []],
    'app_item_update' => [['id'], ['_controller' => 'App\\Controller\\ItemController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/item/update']], [], [], []],
    'app_item_delete' => [['id'], ['_controller' => 'App\\Controller\\ItemController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/item/delete']], [], [], []],
    'app_facture_pdf' => [['factureId'], ['_controller' => 'App\\Controller\\PdfController::facturePdf'], [], [['variable', '/', '[^/]++', 'factureId', true], ['text', '/pdf/facture']], [], [], []],
    'App\Controller\FactureController::index' => [[], ['_controller' => 'App\\Controller\\FactureController::index'], [], [['text', '/facture']], [], [], []],
    'App\Controller\FactureController::create' => [[], ['_controller' => 'App\\Controller\\FactureController::create'], [], [['text', '/facture/create']], [], [], []],
    'App\Controller\FactureController::update' => [['id'], ['_controller' => 'App\\Controller\\FactureController::update'], [], [['text', '/update'], ['variable', '/', '[^/]++', 'id', true], ['text', '/facture']], [], [], []],
    'App\Controller\FactureController::delete' => [['id'], ['_controller' => 'App\\Controller\\FactureController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/facture']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\ItemController::index' => [['factureId'], ['_controller' => 'App\\Controller\\ItemController::index'], [], [['text', '/item/index'], ['variable', '/', '[^/]++', 'factureId', true], ['text', '/facture']], [], [], []],
    'App\Controller\ItemController::create' => [['factureId'], ['_controller' => 'App\\Controller\\ItemController::create'], [], [['variable', '/', '[^/]++', 'factureId', true], ['text', '/item/create']], [], [], []],
    'App\Controller\ItemController::update' => [['id'], ['_controller' => 'App\\Controller\\ItemController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/item/update']], [], [], []],
    'App\Controller\ItemController::delete' => [['id'], ['_controller' => 'App\\Controller\\ItemController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/item/delete']], [], [], []],
    'App\Controller\PdfController::facturePdf' => [['factureId'], ['_controller' => 'App\\Controller\\PdfController::facturePdf'], [], [['variable', '/', '[^/]++', 'factureId', true], ['text', '/pdf/facture']], [], [], []],
];
