<?php

namespace ContainerDSfNxDx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFactureControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fDA1JY8.App\Controller\FactureController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.fDA1JY8'] ?? $container->load('get_ServiceLocator_FDA1JY8Service'));

        if (isset($container->privates['.service_locator.fDA1JY8.App\\Controller\\FactureController::update()'])) {
            return $container->privates['.service_locator.fDA1JY8.App\\Controller\\FactureController::update()'];
        }

        return $container->privates['.service_locator.fDA1JY8.App\\Controller\\FactureController::update()'] = $a->withContext('App\\Controller\\FactureController::update()', $container);
    }
}
