<?php

namespace ContainerDSfNxDx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItemControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hmCQJaR.App\Controller\ItemController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.hmCQJaR'] ?? $container->load('get_ServiceLocator_HmCQJaRService'));

        if (isset($container->privates['.service_locator.hmCQJaR.App\\Controller\\ItemController::update()'])) {
            return $container->privates['.service_locator.hmCQJaR.App\\Controller\\ItemController::update()'];
        }

        return $container->privates['.service_locator.hmCQJaR.App\\Controller\\ItemController::update()'] = $a->withContext('App\\Controller\\ItemController::update()', $container);
    }
}
