<?php

namespace ContainerN7BGaZx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HmCQJaRService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.hmCQJaR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hmCQJaR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'item' => ['privates', '.errored..service_locator.hmCQJaR.App\\Entity\\Item', NULL, 'Cannot autowire service ".service_locator.hmCQJaR": it needs an instance of "App\\Entity\\Item" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'item' => 'App\\Entity\\Item',
            'em' => '?',
        ]);
    }
}
