<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDSfNxDx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDSfNxDx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDSfNxDx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDSfNxDx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDSfNxDx\App_KernelDevDebugContainer([
    'container.build_hash' => 'DSfNxDx',
    'container.build_id' => '2bec08e7',
    'container.build_time' => 1742984434,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDSfNxDx');
